version: '3.12'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:

volumes:
  postgres_data: